name: svg_to_font
description: A tool for converting svg files to a font. To facilitate developers to quickly generate icon font (.ttf) and Flutter icon class, We developed the svg_to_font library.
version: 1.0.2
repository: https://github.com/camus-design/svg_to_font.git

environment:
  sdk: '>=2.16.1 <3.0.0'


dev_dependencies:
  camus_lints: ^1.1.1
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  io: ^1.0.3
  path: ^1.8.0
  recase: ^4.1.0

executables:
  svg_to_font: main
